(source gnu)
(source melpa)

;; auto-complete
(depends-on "auto-complete")
(depends-on "fuzzy")
(depends-on "popup")

;; snippet
(depends-on "yasnippet")

;; Go
(depends-on "go-mode")

;; Python
(depends-on "jedi")
(depends-on "yaml-mode")

;; Shell
(depends-on "quickrun")

;; Javascript
(depends-on "js2-mode")

;; Markup language
(depends-on "web-mode")
(depends-on "emmet-mode")
(depends-on "less-css-mode")

;; markdown
(depends-on "markdown-mode")

;; Setup
(depends-on "init-loader")
(depends-on "exec-path-from-shell")

;; Config
(depends-on "nginx-mode")

;;;; auto-complete sources
(depends-on "ac-slime")
(depends-on "ac-nrepl")
(depends-on "go-autocomplete")
(depends-on "ac-ispell")
(depends-on "ac-etags")
(depends-on "robe")
(depends-on "ac-c-headers")